---
# tasks file for git_clone


- name: Clone Git Repo
  git:
    repo: https://github.com/MarutiJogdand/JavaSpringProject.git
    dest: /root/JavaSpringProject
    clone: yes

- name: Copy war file
  copy:
   src: /root/JavaSpringProject/Compose.war
   dest: /root/application_deployment_ansible/roles/tomcat_installation/files/Compose.war
  
