---

- name: Create EC2 server
  ec2:
    key_name: "{{ keypair_name }}"
    image: ami-049ceee18ac22d417
    wait: yes
    instance_type: t2.micro
    region: "{{ region }}"
    group_id: "sg-09bad65848196207d"
    instance_tags:
        Name: "{{instance_name}}"
    count_tag:
      Name: apacheserver
    exact_count: 1
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- debug:
    var: ec2.instances[0]["public_ip"]

- add_host: 
      name: "{{item['public_ip']}}"  
      groups: NewServer
      ansible_ssh_private_key_file: "/root/aws_tomcat_server/roles/NewPrivateKey.pem"
      ansible_user: ec2-user
  with_items: "{{ec2.instances}}" 

- name: wait for the instances to boot by checking the ssh port
  wait_for: 
      host: "{{item['public_ip']}}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
  with_items:  "{{ec2.instances}}"

