---

#- name: Create EC2 server
#  ec2:
#    key_name: "{{ keypair_name }}"
#    image: ami-0b5cc54be15133c79
#    wait: yes
#    instance_type: t2.micro
#    region: "{{ region }}"
#    group_id: "sg-0bc365b5af269a276"
#    instance_tags:
#        Name: "{{instance_name}}"
#    count_tag:
#      Name: apacheserver
#    exact_count: 1
#    vpc_subnet_id: subnet-05960b60
#    aws_access_key: "{{ aws_access_key }}"
#    aws_secret_key: "{{ aws_secret_key }}"
#  register: ec2

- ec2:
    key_name: "{{ keypair_name }}"
    region: "{{ region }}"
    group: "AnsibleTowerDemo"
    instance_type: t2.micro
    image: ami-0fad7378adf284ce0
    wait: yes
    wait_timeout: 500
    count: 1
    instance_tags:
       Name: "{{instance_name}}"
    monitoring: no
    vpc_subnet_id: subnet-05960b60
    assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2



- debug:
    var: ec2.instances[0]["public_ip"]

- add_host: 
      name: "{{item['public_ip']}}"  
      groups: NewServer
      ansible_ssh_private_key_file: "/var/lib/awx/projects/_6__ansible_poc/roles/NewPrivateKey.pem"
      ansible_user: ec2-user
  with_items: "{{ec2.instances}}" 

- name: wait for the instances to boot by checking the ssh port
  wait_for: 
      host: "{{item['public_ip']}}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
  with_items:  "{{ec2.instances}}"

